# Generated by Django 4.1 on 2022-09-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='gray',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='photo',
            field=models.ImageField(default='SOME STRING', upload_to='gallery/'),
        ),
    ]
