# Generated by Django 4.1 on 2022-09-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_document_document_document_gray_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='gray',
        ),
    ]
