# Generated by Django 4.1 on 2022-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_document_description_remove_document_gray'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='picture_type',
            field=models.CharField(default='black_white', max_length=100),
        ),
    ]
